
quicksilver-book.pdf: quicksilver-book.tex environment-book.tex
	texexec quicksilver-book

all: quicksilver-book.pdf

sweep:
	rm -f *.mp *.log *.tmp *.tui *.tuo tmpscript

clean: sweep
	rm -f *.pdf

