
quicksilver-book.pdf: quicksilver-book.tex environment-book.tex
	context quicksilver-book.tex

all: quicksilver-book.pdf

sweep:
	rm -f *.mp *.log *.tmp *.tui *.tuo *.dvi

clean: sweep
	rm -f *.pdf

